### ISSUE TITLE
Linear from PyTorch must map to Gemm in ONNX

### ISSUE THREAD

**Issue by baijumeswani** [microsoft/onnxscript#1089]
PyTorch Model:

```python
class NeuralNet(torch.nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super().__init__()

        self.fc1 = torch.nn.Linear(input_size, hidden_size)
        self.relu = torch.nn.ReLU()
        self.fc2 = torch.nn.Linear(hidden_size, num_classes)

    def forward(self, input1):
        out = self.fc1(input1)
        out = self.relu(out)
        out = self.fc2(out)
        return out
```

Exporting with torch script based exporter yields:

![image](https://github.com/microsoft/onnxscript/assets/12852605/dd087259-a202-4b7a-ab71-c55d54d68c7f)

which makes sense. It is after all a linear layer followed by a ReLU followed by another Linear layer.

Exporting the same model with torch dynamo based exporter yields:

<img width="263" alt="image" src="https://github.com/microsoft/onnxscript/assets/12852605/f7eb9abb-ba67-4f01-a25a-8e287f83cf72">

Two levels beneath the linear layer, I find:

<img width="380" alt="image" src="https://github.com/microsoft/onnxscript/assets/12852605/03751eb6-3400-4a46-8d04-cb88e0f2012b">

It seems like the Gemm is somehow manifested as a subgraph with matmuls, muls, adds, and castlikes. And digging deeper, I find that this definition comes from https://github.com/microsoft/onnxscript/blob/a981b8add9a4c7e67ad0d28622b23d4c6a55a76e/onnxscript/function_libs/torch_lib/ops/core.py#L220-L229

It seems wasteful that an op as simple as a Gemm needs to be represented as this subgraph. Looking at [this document](https://github.com/microsoft/onnxscript/issues/165), this seems to be a design choice.

> We favor general ops like MatMul than specialized ops like Gemm in the function lib.

But imagine a model having thousands of `Gemm`s. Each `Gemm` is now this subgraph. Which means this optimization/fusion needs to run thousands of times to achieve something that probably can be achieved very easily at the source.

It would benefit ONNX Runtime (inference and training) and the larger ONNX community if this subgraph were represented as a Gemm node after export.

**Comment by baijumeswani** [comment]
cc: @BowenBao @justinchuby

**Comment by justinchuby** [comment]
Gemm is a special case for the op `addmm` (https://github.com/pytorch/pytorch/blob/a6b452dfdcb484d5dfdbb577b74cecbd7021df2e/torch/onnx/symbolic_opset9.py#L645-L652). In the design of torchlib, we wanted the ONNX functions to mirror the aten ops behavior as closely as possible, so that we preserve the richest information for downstream optimization. To be able to use `Gemm` for `addmm`, we need to know the type and rank of the input, which are not assumed to be available at export time.

This kind of fusion should actually be simple for downstream optimization passes by design. We can look at the `aten_addmm` function, its input types and rank when available, then make the substitution. We do need the type and rank information for this which is not available in nested functions though as @BowenBao pointed out in https://github.com/onnx/onnx/issues/5487

**Comment by justinchuby** [comment]
However, for this special case, we may be able to create an overload for supported types to conditionally choose Gemm based on rank.

**Comment by justinchuby** [comment]
So far it looks like the best path forward is for ORT to implement Gemm on spec'ed types and use (1). This way we strive a balance between correctness and the effort needed for fusion.

**Comment by justinchuby** [comment]
Although: if folding is not necessarily easier and the model may run even slower with if branches when unoptimized

**Comment by baijumeswani** [comment]
All solutions offered here are not very helpful since they all require a subgraph computation (to be either folded away or fused to Gemm).

Ideally, the information about the rank of the input matrices as well as the value of alpha and beta are known at export time. Which makes me feel that this should be dealt with at source and not down streamed to another optimization pass at a later time.

This particularly becomes more important for scenarios where the export is an inline operation (such as in ORTModule) and the export time along with other optimization times results in performance penalty for the scenario.

**Comment by baijumeswani** [comment]
cc @pranavsharma for awareness, as I think this would impact inference as well.

**Comment by pranavsharma** [comment]
Thanks @baijumeswani for adding me. 
Exporter team: Please fix this at the export time as ORT is not the only consumer of ONNX graphs. There is a whole ecosystem around ONNX and such changes will break all of them.

**Comment by justinchuby** [comment]
Thanks for this perspective! Happy to explore options here. One of the things that come to mind is as we build out aot optimization capabilities for ONNX graphs, these type of patterns can be optimized away (by the exporter) before the runtime sees the graph. This way tools in the ecosystem can choose to operate on graphs with different levels of generality based on the assumptions they are built against.

**Comment by xadupre** [comment]
Some thoughts related to these issues.

Models can be very big nowadays, anything we don't handle at exporting handle must be taken care of at optimizing time. It is ok for small models but it is still ok on bigger models with thousands of operators? Looking for patterns in such graphs adds significant time. Maybe we should start tracking the converters performance (converting time, optimizing time with onnxruntime).

One particular case with onnx-script, it is rare but it can happen.

```python
if beta == 0:
   B = op.Matmul(X, np.array(...))
else:
   B = op.Matmul(X, np.array(....))
```

onnx-script will convert this into 3 operators (if + 2x matmul) and 2 initializers. Then an optimization will fold the constants and keep one operator and one initializer. What if both initializers are very big? We would add unnecessary tensors to the model making it unnecessary big.

Another one, again, it is rare but it is possible:

```python
B = op.Matmul(A, op.CastLike(np.array([....], dtype=np.float32), B)
```

The onnx model will always keep float tensors but if the model is float16, this could be reduced by half and the exported model could be smaller.

**Comment by justinchuby** [comment]
> onnx-script will convert this into 3 operators (if + 2x matmul) and 2 initializers

I think a concreate usage will help discussion here. Since aten operators take all large tensors as input, I don't see we will duplicate large tensors in functions (they are more likely scalars).

> The onnx model will always keep float tensors but if the model is float16, this could be reduced by half and the exported model could be smaller.

This I think presents a similar issue, where all castlike'd tensors tend to be single element tensors (scalars) that don't take up spaces. The exported initializers will be float16 if the model is dealing with float16 inputs.

**Comment by gramalingam** [comment]
A few comments:

- Seems better for exporter to emit Gemm for all legal types when possible (without worrying about whether ORT has Gemm kernels for those types ... that is more of an ORT issue). That is, option (1) seems preferable over option (2) in Justin's note.
- It makes sense for the exporter to run some set of standard optimizations as post-processing to hide the complexity discussed above from downstream users to the extent possible.
- For example, types can be assumed to be known. So, CastLike should be eliminated, constant-folded away, ranks are typically known, and the if-conditions checking ranks can be constant-folded away, etc.

**Comment by justinchuby** [comment]
Thanks @gramalingam. I will change to (1) in the implementation. Fortunately the rest of the complexity for this op is no longer a concern because we realized Gemm can handle the op. But these point do help when we counter new instances like this
