### ISSUE TITLE
Support indexing on multi return nodes

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1107]
Operators like Unique can have one or more returns, depending on how many are declared in the graph. In ONNX Script eager mode, since there isn’t a way to control how many outputs the node should return, onnxscript returns all of the values. 

E.g. we need to write 

```
(a, b, c, d) = op.Unique(...)
```

for eager mode to work. This can be an issue because if we only need the first two outputs, the last two will be computed as discarded, which can be wasteful. 

Script mode however with the knowledge of the full ast knows the number of returns, so it is possible to write

```
a, b = op.Unique(...)
```

in script mode. This will fail in eager mode with ”too many values to unpack”. 

I propose that we allow the script mode to understand slicing in return values, which allows us to write

```
a, b = op.Unique(...)[:2]
```

This way the script mode knows we need only the first outputs as usual, and eager will simply leverage slicing on Python tuple to get the first outputs. 

It would be good for Script to additionally understand

```
a, b = op.Unique(...)[2:4]
```

for example. I imagine we will need to create dummy values for the first two outputs (or is `""` fine?) which are simply unused in this case.

@gramalingam 

Related: https://github.com/microsoft/onnxscript/issues/1106

**Comment by gramalingam** [comment]
> This can be an issue because if we only need the first two outputs, the last two will be computed as discarded, which can be wasteful.

I am a bit confused about the motivation: it is not clear to me how the slicing `[:2]` eliminates the redundant computation ... semantically it is equivalent to unpacking it into 4 values, where two are never used.

Are you trying to produce a NodeProto where the outputs are set to "" here? If so, I think one option would be check if the unpacked "c" and "d" are unused subsequently and replace them by "" in the proto form. This is, essentially, an ONNX-to-ONNX optimization. (It is probably even better left to backends, but we can do it too.)

Or, did I misunderstand?

**Comment by justinchuby** [comment]
> Are you trying to produce a NodeProto where the outputs are set to "" here? If so, I think one option would be check if the unpacked "c" and "d" are unused subsequently and replace them by "" in the proto form. This is, essentially, an ONNX-to-ONNX optimization. (It is probably even better left to backends, but we can do it too.)

I think that works too!
