### ISSUE TITLE
AttributeError: module 'onnxscript.function_libs.torch_lib.ops.core' has no attribute 'aten_bitwise_not_bool'

### ISSUE THREAD

**Issue by jinwonkim93** [microsoft/onnxscript#1117]
Hi i am encountering attribute error. 
how can i fix this issue?
onnxscript-0.1.0.dev20231030
torch==2.1.0
![image](https://github.com/microsoft/onnxscript/assets/26476095/875feace-9044-4cd3-bcda-a3436bee8664)

onnxscript-0.1.0.dev20231030
torch-nightly
![image](https://github.com/microsoft/onnxscript/assets/26476095/63c71629-47a9-4e93-8358-0e51c786a89f)

well it is confusing me now, is it pytorch related issue?

**Comment by jinwonkim93** [comment]
i will close this issue since it is related to pytorch.

**Comment by justinchuby** [comment]
The code you show looks like from an older version of PyTorch and not 2.1. I would make sure the environment is consistent and correct
