### ISSUE TITLE
[torchlib] Implement `aten::_scaled_dot_product_efficient_attention.default`

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxscript#1160]
From models. This op is emitted from **cuda export only**.

        cait_m36_384
        deit_base_distilled_patch16_224
        crossvit_9_240
        mobilevit_s
        pit_b_224
        nanogpt
        timm_vision_transformer
        beit_base_patch16_224
        stable_diffusion_unet

From https://github.com/microsoft/onnx-converters-private/issues/196

cc @justinchuby

**Comment by titaiwangms** [comment]
Does it make any difference on torchlib implementation if the op is meant for CUDA? If not, I can take this real quick.
