### ISSUE TITLE
Wrong shape of mean and variance in _aten_native_batch_norm_inference_onnx

### ISSUE THREAD

**Issue by yuanyao-nv** [microsoft/onnxscript#1256]
In the implementation of `_aten_native_batch_norm_inference_onnx()` the shapes of mean and variance seem wrong. They should be length-C vectors according to the ONNX spec but the current aten definitions result in scalars.
https://github.com/microsoft/onnxscript/blob/main/onnxscript/function_libs/torch_lib/ops/core.py#L5657-L5658
```
    empty_mean = op.CastLike(op.Shape(input, start=0, end=0), norm)
    empty_var = op.CastLike(op.Shape(input, start=0, end=0), norm)
```

Additionally, in some of the dynamo exported models, I see that the `running_mean` and `running_var` inputs also have wrong data type:
![image](https://github.com/microsoft/onnxscript/assets/99693700/d77b1007-cbf8-463b-b470-8ce8d734ffc1)
![image](https://github.com/microsoft/onnxscript/assets/99693700/fae68f3f-27ec-4698-813b-0097334ca0cc)

**Comment by justinchuby** [comment]
You are absolutely right :D. We did not implement it because the model did not use those outputs at the time. Contributions are welcome. Strange it is "true" though.

**Comment by BowenBao** [comment]
I think in most cases (where these outputs are unused), they are optimized away by function aware onnx rewriter.
It might indeed prevent the use of onnx shape inference before rewriting, since the phony outputs would still exist in the graph and lead to errors.

**Comment by titaiwangms** [comment]
We need to look into that `running: boolean`

**Comment by justinchuby** [comment]
The shapes follow what PyTorch expects. When training is False, they are empty.

**Comment by justinchuby** [comment]
We fixed the shapes for GPU.
