### ISSUE TITLE
Illegal "IsScalar" node encountered in exported ONNX model

### ISSUE THREAD

**Issue by yuanyao-nv** [microsoft/onnxscript#1263]
An exported model contains an `IsScalar` op which is not in the ONNX spec.
![image](https://github.com/microsoft/onnxscript/assets/99693700/e668c040-151f-4c5f-b978-96d7609e3807)

Seems like it comes from the use of `common_ops.IsScalar` in `aten_mean_dim`.

Env:
torch 2.3.0.dev20240202+cu121
onnxscript 0.1.0.dev20240203
MONAI installed with ` pip3 install git+https://github.com/Project-MONAI/MONAI@0.8.1#egg=MONAI`

**Comment by justinchuby** [comment]
IsScalar is a function which should be part of the model local functions. How was the model exported?

**Comment by yuanyao-nv** [comment]
This is the export script:
```
import torch
from monai.networks.nets import DenseNet

def DenseNetDataloader():
    yield torch.randn(1,1,128,128).to("cuda")

model = lambda : DenseNet(
            init_features=64,
            growth_rate=32,
            block_config=[6, 12, 24, 16],
            spatial_dims=2,
            in_channels=1,
            out_channels=15
        )
data = next(DenseNetDataloader())

model = model().eval().to('cuda')

export_output = torch.onnx.dynamo_export(
    model,
    data,
)
export_output.save('Clara_DenseNet_dynamo.onnx')
```

**Comment by justinchuby** [comment]
Was the error raised from the onnx checker?

**Comment by justinchuby** [comment]
Could you attach the exported ONNX file?

**Comment by yuanyao-nv** [comment]
ONNX checker actually doesn't give any error. The error was raised by TensorRT.

I'm checking with the relevant parties whether I can directly share the model. Did the export script I attached above work for you? I used the NGC pytorch container `docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:xx.xx-py3` and installed torch, onnxscript and MONAI as I noted in the description. You might also need to install some dependencies manually:
```
pip install hydra-core sentencepiece youtokentome transformers inflect pyannote.core pyannote.metrics editdistance jiwer h5py sacremoses pytorch-lightning webdataset ijson wandb
```

**Comment by justinchuby** [comment]
On thing I would check is if IsScalar is defined as one of the model local functions.

**Comment by yuanyao-nv** [comment]
See the model attached here: https://drive.google.com/drive/folders/1f3O9Z2zOTFGlh1grY1l2vQWxE7koQb2j?usp=drive_link
It seems like IsScalar is a node rather than a local function. It's location is 
torch_nn_modules_container_Sequential_class_layers_1, torch_nn_modules_pooling_AdaptiveAvgPool2d_class_layers_pool_1, aten_mean_dim.

**Comment by justinchuby** [comment]
Looks like the gdrive folder is empty

**Comment by justinchuby** [comment]
IsScalar should be defined:

```python
import onnx
m = onnx.load("Clara_DenseNet_dynamo.onnx")
print(m.functions[-1])
```

yields

```
name: "IsScalar"
input: "input"
output: "return_val"
node {
  input: "input"
  output: "tmp"
  name: "n0"
  op_type: "Shape"
  domain: ""
}
node {
  input: "tmp"
  output: "tmp_0"
  name: "n1"
  op_type: "Size"
  domain: ""
}
node {
  output: "tmp_1"
  name: "n2"
  op_type: "Constant"
  attribute {
    name: "value_int"
    i: 0
    type: INT
  }
  domain: ""
}
node {
  input: "tmp_0"
  input: "tmp_1"
  output: "return_val"
  name: "n3"
  op_type: "Equal"
  domain: ""
}
doc_string: "Return whether the input has rank 0, or is a scalar."
opset_import {
  domain: ""
  version: 18
}
domain: "pkg.onnxscript.torch_lib.common"
```

But netron does not show the function definition of it. 🤔 I wonder what went wrong?

**Comment by yuanyao-nv** [comment]
Also I noticed if run the inliner and then onnx-rewriter on this model, the optimized graph still contains the IsScalar node:
![image](https://github.com/microsoft/onnxscript/assets/99693700/5aa0fd60-215b-4603-9638-768fe321c539)

**Comment by justinchuby** [comment]
That's an issue. @gramalingam @xadupre @BowenBao do you have any guesses?

**Comment by BowenBao** [comment]
I have also encountered the inliner issue around `IsScalar`. The node is not inlined yet its FunctionProto is removed.

**Comment by xadupre** [comment]
I have also some trouble when applying the inliner on a llama model. onnxruntime complained about a similar issue so I usually skip the inline part. I checked that the graph obtained with dynamo + onnx-rewriter + onnxruntime optimization looks ok and does not contain any local function any more. I suggest skipping the inliner until this bug is fixed in onnx.

**Comment by justinchuby** [comment]
@BowenBao I have a guess: the nn module functions need to import the torchscript common domain.

**Comment by BowenBao** [comment]
You are right. Partly related to https://github.com/microsoft/onnxscript/issues/834, where in a related PR a workaround was added to always insert common domain on main graph level. So nn module functions are missing those.

**Comment by justinchuby** [comment]
Looks like the inliner works:

```python
import onnx
import onnx.inliner

model = onnx.load("Clara_DenseNet_dynamo.onnx")
inlined = onnx.inliner.inline_selected_functions(model, [("pkg.onnxscript.torch_lib.common", "Rank"), ("pkg.onnxscript.torch_lib.common", "IsScalar")])
onnx.save_model(inlined, "Clara_DenseNet_dynamo_inlined.onnx")
```

![image](https://github.com/microsoft/onnxscript/assets/11205048/e37ac358-a54a-4492-ae7e-5c0e70b38c17)

**Comment by justinchuby** [comment]
The fully inlined model also seems fine:

![image](https://github.com/microsoft/onnxscript/assets/11205048/a2632a7c-92e3-4678-8079-6699db70e774)

I used the latest `onnx-weekly` build.

**Comment by justinchuby** [comment]
Created https://github.com/lutzroeder/netron/issues/1225 for netron.

**Comment by justinchuby** [comment]
Netron is fixed. It may be a bug in TensorRT.

**Comment by BowenBao** [comment]
@justinchuby is the above inliner result without using my (now reverted) change in onnxscript? I recall observing `IsScalar` in full inlined graph before, could you kindly check the result of onnx 1.15 inliner?

**Comment by yuanyao-nv** [comment]
I observe a similar issue with a problematic Rank node in maxpool model:
![image](https://github.com/microsoft/onnxscript/assets/99693700/03a77557-2d8c-4285-8a68-02efb64222f5)
My package versions are:
torch                     2.3.0.dev20240209+cu121
onnxscript                0.1.0.dev20240209

Script is:
```
class Model(nn.Module):
  def __init__(self):
      super().__init__()
      self.mp = torch.nn.MaxPool2d(3, stride=2)

  def forward(self, tensor_x: torch.Tensor):
      output = self.mp(tensor_x)
      return output

def Dataloader():
    yield torch.randn(20, 16, 50, 32).cuda()

model = Model()
data = next(Dataloader())

export_output = torch.onnx.dynamo_export(
    model.eval().to('cuda'),
    data,
)
export_output.save('maxpool_dynamo.onnx')
```

**Comment by justinchuby** [comment]
Is this an inlined model? If not it looks expected. Netron has recently added a patch

**Comment by gramalingam** [comment]
Hmmm. There was an issue in the exporter/onnxscript relating to gathering all necessary imports (re. the reverted fix, as Bowen mentions above). That does still need to be fixed, right?

**Comment by BowenBao** [comment]
> Hmmm. There was an issue in the exporter/onnxscript relating to gathering all necessary imports (re. the reverted fix, as Bowen mentions above). That does still need to be fixed, right?

Both model opset_import and functions opset_imports are actually correct without the fix. So it is not needed. 

I have checked that the inliner in onnx-weekly works correctly on OP's model, where as inliner in onnx 1.15 would leave out an `IsScalar` node inside an if subgraph, while removing `IsScalar` from model.functions.

![image](https://github.com/microsoft/onnxscript/assets/9376104/8c9c9f9d-03c6-4724-8762-dfe8e31acac7)

![image](https://github.com/microsoft/onnxscript/assets/9376104/2c2df797-8b1a-479c-a6cb-e6c878ec77f5)

@yuanyao-nv the OP issues turns out to be bug in (previous) Netron display and onnx 1.15 inliner. Both should be fixed in latest version.

**Comment by gramalingam** [comment]
> > Hmmm. There was an issue in the exporter/onnxscript relating to gathering all necessary imports (re. the reverted fix, as Bowen mentions above). That does still need to be fixed, right?
> 
> Both model opset_import and functions opset_imports are actually correct without the fix. So it is not needed.
> 
> I have checked that the inliner in onnx-weekly works correctly on OP's model, where as inliner in onnx 1.15 would leave out an `IsScalar` node inside an if subgraph, while removing `IsScalar` from model.functions.
> 
> ![image](https://private-user-images.githubusercontent.com/9376104/304173229-8c9c9f9d-03c6-4724-8762-dfe8e31acac7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NzkwMTUsIm5iZiI6MTcwNzc3ODcxNSwicGF0aCI6Ii85Mzc2MTA0LzMwNDE3MzIyOS04YzljOWY5ZC0wM2M2LTQ3MjQtODc2Mi1kZmU4ZTMxYWNhYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMjI1ODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk1ZTM1MzFhNzkxYzFlOGJlMWY5ZDk2Y2EwMWQ1NzY2MzM0YWZlOGJiOTU3ZWU4YTIwMGNmYTcwMGExNzViMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XMlybUUl2JW7KBEp3dyeoxV8NpPJ5DBi-VzkEdeGCCQ)
> 
> ![image](https://private-user-images.githubusercontent.com/9376104/304172969-2c2df797-8b1a-479c-a6cb-e6c878ec77f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NzkwMTUsIm5iZiI6MTcwNzc3ODcxNSwicGF0aCI6Ii85Mzc2MTA0LzMwNDE3Mjk2OS0yYzJkZjc5Ny04YjFhLTQ3OWMtYTZjYi1lNmM4NzhlYzc3ZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMjI1ODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDRiYWY0MjA4NTRkN2YyY2IyOGIwMDdiYzU0YWNkNDQ1NjAzYTcxNjNiYWU4YjJlMWU0Y2E3YjAxNTg0ZTEzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cMiWfLMrkEEZl_ynPnTkYfwfGf-P9pVUrj5nigpa8mw)
> 
> @yuanyao-nv the OP issues turns out to be bug in (previous) Netron display and onnx 1.15 inliner. Both should be fixed in latest version.

Makes sense. Thanks!

**Comment by yuanyao-nv** [comment]
Verified that the issue is fixed now. Thanks!
