### ISSUE TITLE
Repeated variables in a rewriter pattern

### ISSUE THREAD

**Issue by gramalingam** [microsoft/onnxscript#1386]
Is a repeated variable in a pattern allowed and what is its meaning?

A repeated variable in a pattern is useful and has a reasonable meaning. A simple example is an optimization to rewrite `X*A + X*B` into `X*(A+B)`. The essential meaning is that the values bound to X at the two different places must be the same value.

At a detailed level: there are two interpretations possible for the notion of "same value": similar to the notions of pointer/reference equality and value-equality (in several languages) for Value in the IR. The easy-to-check and most-useful notion is that of pointer/reference equality ... the values are the same Value object in the IR. The second notion is more powerful (checking whether two expressions in the IR will have the same runtime-value), but also harder to check.

To start with, using the first notion of equality should be reasonable

**Comment by xadupre** [comment]
It is supported by the multi-output pattern matcher.
