### ISSUE TITLE
Contribution welcome

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1433]
⭐ Use this filter to find all issues that welcome contributions: https://github.com/microsoft/onnxscript/issues?q=is%3Aissue+is%3Aopen++label%3A%22contribution+welcome%22+

**Comment by thiagocrepaldi** [comment]
maybe add this to a wiki or something? public issues as documentation is not ideal

**Comment by justinchuby** [comment]
This is a pin issue so it is a good entry point for anyone browsing the issues. Any suggestions? Wiki is not ideal as it is typically not the landing page.
