### ISSUE TITLE
[IR] Update opset import when a function is added to a model

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1444]
Currently functions are stored in a dictionary in the model. We should update the opset imports when functions are added.

**Comment by titaiwangms** [comment]
Another thought in this PR. Should we also take care the case that user forgets to add custom domain into their ir.Function? Let's say we have a onnx.FunctionProto without adding com.mircorsoft into opset_imports, but actually use their ops?

**Comment by justinchuby** [comment]
I can think of two options:

1. Add the domain when the node is being inserted to the graph. This is doable and is O(1), but we may not know which opset version the user wants to use, and there may be version conflicts we need to decide how to handle.
2. Or we can do that in a pass, where we import all opsets by iterating over the nodes, fail or resolve when hitting a version conflict (still we need to find a way to let users specify the opset).
