### ISSUE TITLE
Add onnx.checker.check_model into optimizer/rewriter

### ISSUE THREAD

**Issue by titaiwangms** [microsoft/onnxscript#1457]
Optimizer and rewriter could generate models that are not following check rules. For example #1443 and https://github.com/microsoft/onnxscript/pull/1451#discussion_r1580104737, these models are optimized/rewrote without passing onnx.checker.

cc @gramalingam @BowenBao @justinchuby

**Comment by justinchuby** [comment]
We should add it in tests instead, or enable in a debug mode.

**Comment by titaiwangms** [comment]
However, in optimizer, we do need model to pass checker: https://github.com/microsoft/onnxscript/issues/1443#issuecomment-2078275333.
