### ISSUE TITLE
Pass to convert a model with bfloat16 inputs to float16

### ISSUE THREAD

**Issue by thiagocrepaldi** [microsoft/onnxscript#1462]
ONNX Runtime doesn't support onnx models with bfloat16 inputs. Thus, given an onnx model with bfloat16 inputs, we need a pass that converts inputs to float16

the repro is a unit test at <pytorch>/test/onnx/test_fx_to_onnx_with_onnxruntime.py:
 
```python
    def test_bfloat16_serialization(self):
        class MyLinear(nn.Module):
            def __init__(self):
                super().__init__()
                self.fc1 = nn.Linear(10, 5, bias=False, dtype=torch.bfloat16)
            def forward(self, tensor_x: torch.Tensor):
                return self.fc1(tensor_x)
        tensor_x = torch.rand((3, 10), dtype=torch.bfloat16)
        onnx_program = torch.onnx.dynamo_export(MyLinear(), tensor_x)
        with tempfile.NamedTemporaryFile(suffix=".onnx") as tmp_onnx_file:
            onnx_program.save(
                tmp_onnx_file.name, model_state=MyLinear().state_dict()
            )
        self.run_test_with_fx_to_onnx_exporter_and_onnx_runtime(MyLinear(), (tensor_x,))
```

**Comment by justinchuby** [comment]
Looks like only the c++ api supports bfloat16 https://github.com/microsoft/onnxruntime/issues/13001. Do you think this pass can be a utility we provide? It may be risky to assume users wants float16 inputs when they export, if this pass is enabled by default.

**Comment by thiagocrepaldi** [comment]
> Looks like only the c++ api supports bfloat16 [microsoft/onnxruntime#13001](https://github.com/microsoft/onnxruntime/issues/13001). Do you think this pass can be a utility we provide? It may be risky to assume users wants float16 inputs when they export, if this pass is enabled by default.

until numpy supports bfloat16, users may want float32 - which they can already get by using float32 input - or float16 in case they want to save memory

**Comment by thiagocrepaldi** [comment]
This is an ORT only optimization, which must be applied along with the other ort-specific rewrites

**Comment by justinchuby** [comment]
Also created https://github.com/microsoft/onnxruntime/issues/20578
