### ISSUE TITLE
[IR] Allow values as outputs to ir.Node initializer

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1504]
Sometimes we may want to create the outputs first, before creating the node (when the nodes is not sorted, for example, or when we want to specify the names/shapes etc. to the Value). Create an `outputs` parameter in the ir.Node initializer.

**Comment by gramalingam** [comment]
One case which does show up is giving names for output values when creating a node, eg. via `output=["name1", "name2"]` ... hope that is covered here.

**Comment by justinchuby** [comment]
Fixed by https://github.com/microsoft/onnxscript/pull/1507

**Comment by justinchuby** [comment]
> One case which does show up is giving names for output values when creating a node, eg. via `output=["name1", "name2"]` ... hope that is covered here.

This is possible with

```python
outputs=[ir.Value(..., name="name1"), ...]
```
