### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1520]
https://github.com/microsoft/onnxscript/blob/main/examples/pattern_rewriting.py is broken. cc @shubhambhokare1 @gramalingam

**Comment by shubhambhokare1** [comment]
@justinchuby will take a look at this

**Comment by gramalingam** [comment]
I think this was fixed by https://github.com/microsoft/onnxscript/pull/1521 ... so, I will close this. (But, as discussed there, we should eliminate this folder in favor of the docs folder.)
