### ISSUE TITLE
[IR][doc] ONNX IR online doc is showing 'FileNotFoundError'

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxscript#1600]
From https://onnxscript.ai/intermediate_representation/getting_started.html

![image](https://github.com/microsoft/onnxscript/assets/9376104/b22f7e1d-46f9-46f6-95a4-ab2650fe777f)

**Comment by justinchuby** [comment]
Now showing `DecodeError: Error parsing message`. Need to investigate further.
