### ISSUE TITLE
Missing `black` formatter and `torchvision` libraries in `requirements.txt`

### ISSUE THREAD

**Issue by hrishi121** [microsoft/onnxscript#1619]
1. `opgen` runs `black` code formatter and `isort` at this [line](https://github.com/microsoft/onnxscript/blob/4a9b04e694fd670cf5687312119f6c0aadd3b134/opgen/__main__.py#L76), however, [/lintrunner/requirements.txt](https://github.com/microsoft/onnxscript/blob/main/requirements/lintrunner/requirements.txt) seems to be missing both `black` and `isort`. Or did I miss a step?
ONNX repo seems to have explicitly added `black` and `isort` in the [requirements-lintrunner.txt](https://github.com/onnx/onnx/blob/6f7ff971b2a9beec104e1480c9945f92737a63de/requirements-lintrunner.txt#L8C1-L10C14)

3. When running `ops_test.py` unit-test, it tries to import `torchvision` (through the `extra_opinfo.py` file). However, when installing `requirements-dev.txt`, it misses out on installing the `torchvision` library

**Comment by justinchuby** [comment]
1. We don't use black anymore. We have moved to use ruff format. The opgen code can be updated and the formatters should be removed.

2. Feel free to create a PR. Thanks!

**Comment by hrishi121** [comment]
Ah ok, thank you! Yes, I'll submit a PR for this

**Comment by hrishi121** [comment]
In the above PR #1634, should I also replace

`subprocess.check_call(["black", "--quiet", *paths])`
`subprocess.check_call(["isort", "--quiet", *paths])`

with 

`subprocess.check_call(["ruff", "--quiet", *paths])`

or will this be rectified by someone else in a separate PR for opgen code?

**Comment by justinchuby** [comment]
You may remove the two lines. Thanks!
