### ISSUE TITLE
[torchlib] Implement missing operators uncovered by torch.onnx tests

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1644]
**NOTE**: Some of these may just be incorrectly registered. In this case update the `@torch_op` decorator call in the corresponding functions to register them correctly. It's usually just correcting the overload names. "default" overload can be omitted in names. E.g.

`aten.add.Scalar` -> `@torch_op("aten::add.Scalar")`
`aten.glu.default` -> `@torch_op("aten::glu")`

- [x] Implement `<OpOverload(op='aten.__rshift__', overload='Scalar')>` https://github.com/microsoft/onnxscript/pull/1742
- [ ] Implement <OpOverload(op='aten._adaptive_avg_pool2d', overload='default')>
- [ ] Implement <OpOverload(op='aten._cdist_forward', overload='default')>
- [ ] Implement <OpOverload(op='aten._convolution', overload='default')>
- [ ] Implement <OpOverload(op='aten._fake_quantize_per_tensor_affine_cachemask_tensor_qparams', overload='default')>
- [ ] Implement <OpOverload(op='aten._linalg_det', overload='default')>
- [ ] Implement <OpOverload(op='aten._linalg_slogdet', overload='default')>
- [x] Implement <OpOverload(op='aten._prelu_kernel', overload='default')>
- [x] Implement <OpOverload(op='aten.add', overload='Scalar')>
- [x] Implement <OpOverload(op='aten.add', overload='Tensor')>
- [ ] Implement <OpOverload(op='aten.affine_grid_generator', overload='default')>
- [ ] Implement <OpOverload(op='aten.aminmax', overload='default')>
- [ ] Implement <OpOverload(op='aten.binary_cross_entropy_with_logits', overload='default')>
- [ ] Implement <OpOverload(op='aten.bitwise_and', overload='Tensor')>
- [ ] Implement <OpOverload(op='aten.bucketize', overload='Tensor')>
- [ ] Implement <OpOverload(op='aten.conv_tbc', overload='default')>
- [ ] Implement <OpOverload(op='aten.fake_quantize_per_tensor_affine_cachemask', overload='default')>
- [x] Implement <OpOverload(op='aten.fill', overload='Scalar')>
- [x] Implement <OpOverload(op='aten.fmod', overload='Scalar')>
- [x] Implement <OpOverload(op='aten.fmod', overload='Tensor')>
- [x] Implement <OpOverload(op='aten.glu', overload='default')> @shubhambhokare1 
- [ ] Implement <OpOverload(op='aten.grid_sampler_3d', overload='default')>
- [ ] Implement <OpOverload(op='aten.hann_window', overload='default')>
- [ ] Implement <OpOverload(op='aten.im2col', overload='default')>
- [ ] Implement <OpOverload(op='aten.index_add', overload='default')>
- [ ] Implement <OpOverload(op='aten.index_copy', overload='default')>
- [ ] Implement <OpOverload(op='aten.index_fill', overload='int_Scalar')>
- [ ] Implement <OpOverload(op='aten.index_put', overload='default')>
- [x] Implement <OpOverload(op='aten.le', overload='Scalar')>
- [x] Implement <OpOverload(op='aten.lerp', overload='Scalar')>
- [ ] Implement <OpOverload(op='aten.linalg_cross', overload='default')>
- [ ] Implement <OpOverload(op='aten.masked_scatter', overload='default')>
- [ ] Implement <OpOverload(op='aten.masked_select', overload='default')>
- [x] Implement <OpOverload(op='aten.mv', overload='default')>
- [ ] Implement <OpOverload(op='aten.nan_to_num', overload='default')>
- [ ] Implement <OpOverload(op='aten.nll_loss2d_forward', overload='default')>
- [x] Implement <OpOverload(op='aten.nll_loss_forward', overload='default')>
- [ ] Implement <OpOverload(op='aten.norm', overload='ScalarOpt_dim_dtype')>
- [x] Implement <OpOverload(op='aten.pixel_unshuffle', overload='default')>
- [x] Implement <OpOverload(op='aten.pow', overload='Scalar')>
- [x] Implement <OpOverload(op='aten.prod', overload='dim_int')>
- [x] Implement <OpOverload(op='aten.remainder', overload='Scalar')>
- [x] Implement <OpOverload(op='aten.remainder', overload='Tensor')>
- [ ] Implement <OpOverload(op='aten.repeat_interleave', overload='Tensor')>
- [x] Implement <OpOverload(op='aten.rsub', overload='Tensor')>
- [ ] Implement <OpOverload(op='aten.scatter', overload='src')>
- [ ] Implement <OpOverload(op='aten.scatter', overload='value')>
- [x] Implement <OpOverload(op='aten.silu', overload='default')>
- [x] Implement <OpOverload(op='aten.sort', overload='default')>
- [x] Implement <OpOverload(op='aten.std', overload='correction')>  https://github.com/microsoft/onnxscript/pull/1747
- [x] Implement <OpOverload(op='aten.std_mean', overload='correction')> https://github.com/microsoft/onnxscript/pull/1748#issuecomment-2243988086
- [x] Implement <OpOverload(op='aten.sym_size', overload='int')>
- [ ] Implement <OpOverload(op='aten.take', overload='default')>
- [ ] Implement <OpOverload(op='aten.unsafe_split', overload='Tensor')>
- [ ] Implement <OpOverload(op='torchvision.nms', overload='default')>
- [ ] Implement <OpOverload(op='torchvision.roi_align', overload='default')>
- [ ] Implement <OpOverload(op='torchvision.roi_pool', overload='default')>
- [x] Implement <OpOverload(op='aten.group_norm', overload='default')> #1750

**Comment by justinchuby** [comment]
```
- func: type_as(Tensor self, Tensor other) -> Tensor
  variants: method
```

**Comment by justinchuby** [comment]
```
<OpOverload(op='aten.group_norm', overload='default')
```

**Comment by justinchuby** [comment]
- `aten.std.dim`:     No decompositions registered for the real-valued input. Example node: `%std_1 : [num_users=1] = call_function[target=torch.ops.aten.std.dim](args = (%add_4, [-1], True, True), kwargs = {})`. All nodes: `[std_1, std_2, std_3, std_4, std_5, std_6, std_7, std_8, std_9, std_10, std_11, std_12, std_13, std_14, std_15, std_16, std_17, std_18, std_19, std_20, std_21, std_22, std_23]`
- `aten.std.correction`:     No decompositions registered for the real-valued input. Example node: `%std : [num_users=1] = call_function[target=torch.ops.aten.std.correction](args = (%convert_element_type_default, [-1], True, True), kwargs = {})`. All nodes: `[std]`
- `aten.add.Tensor`:     All overloads did not match the node `%add_2 : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%std, %b_lifted_tensor_210), kwargs = {})`.
    - Failed to match overload `OnnxFunction(<function aten_add at 0x7feb3362b420>)`: Parameter type not compatible with argument: param=`other: TReal`, assigned_types=`{'TReal': Tensor(FLOAT16)}`, arg=`DOUBLE`
    - Failed to match overload `OnnxFunction(<function aten_logical_or at 0x7feb331a0ae0>)`: Parameter type not compatible with argument: param=`self: T_self`, assigned_types=`{}`, arg=`FLOAT16`. Example node: `%add_2 : [num_users=1] = call_function[target=torch.ops.aten.add.Tensor](args = (%std, %b_lifted_tensor_210), kwargs = {})`. All nodes: `[add_2, add_5, add_8, add_11, add_14, add_17, add_20, add_23, add_26, add_29, add_32, add_35, add_38, add_41, add_44, add_47, add_50, add_53, add_56, add_59, add_62, add_65, add_68, add_71]`

**Comment by justinchuby** [comment]
TypeError: aten_linspace() got an unexpected keyword argument 'device'

**Comment by justinchuby** [comment]
- `aten.pad.default`:     No decompositions registered for the real-valued input. Example node: `%pad : [num_users=1] = call_function[target=torch.ops.aten.pad.default](args = (%x, [0, 1, 0, 1], constant, 0.0), kwargs = {})`. All nodes: `[pad, pad_1, pad_2, pad_3, pad_4, pad_5, pad_6, pad_7, pad_8, pad_9, pad_10, pad_11, pad_12, pad_13, pad_14]`

**Comment by justinchuby** [comment]
- `aten.multiply.Tensor`:     No decompositions registered for the real-valued input. Example node: `%multiply : [num_users=1] = call_function[target=torch.ops.aten.multiply.Tensor](args = (%transpose_2, %linear), kwargs = {})`. All nodes: `[multiply, multiply_1, multiply_2, multiply_3, multiply_4, multiply_5, multiply_6, multiply_7, multiply_8, multiply_9, multiply_10, multiply_11]`

**Comment by justinchuby** [comment]
- `aten.where.Scalar`:     No decompositions registered for the real-valued input. Example node: `%where_1 : [num_users=2] = call_function[target=torch.ops.aten.where.Scalar](args = (%any_1, 64504.0, 65504.0), kwargs = {})`. All nodes: `[where_1, where_2, where_3, where_4, where_5, where_6, where_7, where_8, where_9, where_10, where_11, where_12, where_14, where_15, where_16, where_17, where_18, where_19, where_20, where_21, where_22, where_23, where_24, where_25, where_26, where_27, where_28, where_29, where_30, where_31]`

**Comment by justinchuby** [comment]
- https://github.com/microsoft/onnxscript/issues/1749

**Comment by titaiwangms** [comment]
> * `aten.cudnn_batch_norm.default`:     No decompositions registered for the real-valued input. Example node: `%cudnn_batch_norm : [num_users=1] = call_function[target=torch.ops.aten.cudnn_batch_norm.default](args = (%conv2d, %p_patch_embed_proj_0_1_weight, %p_patch_embed_proj_0_1_bias, %b_patch_embed_proj_0_1_running_mean, %b_patch_embed_proj_0_1_running_var, False, 0.1, 1e-05), kwargs = {})`. All nodes: `[cudnn_batch_norm, cudnn_batch_norm_1, cudnn_batch_norm_2, cudnn_batch_norm_3, cudnn_batch_norm_4, cudnn_batch_norm_5, cudnn_batch_norm_6, cudnn_batch_norm_7, cudnn_batch_norm_8, cudnn_batch_norm_9, cudnn_batch_norm_10, cudnn_batch_norm_11, cudnn_batch_norm_12, cudnn_batch_norm_13, cudnn_batch_norm_14, cudnn_batch_norm_15, cudnn_batch_norm_16, cudnn_batch_norm_17, cudnn_batch_norm_18, cudnn_batch_norm_19, cudnn_batch_norm_20, cudnn_batch_norm_21, cudnn_batch_norm_22, cudnn_batch_norm_23, cudnn_batch_norm_24, cudnn_batch_norm_25, cudnn_batch_norm_26]`
> 
> assigned @titaiwangms

@justinchuby Do we still need this after the decom is fixed?

**Comment by justinchuby** [comment]
nll_loss_forward

created with cross_entropy_loss. Needed because if decomposed there is a sum() step which may overflow for float16

**Comment by justinchuby** [comment]
> > * `aten.cudnn_batch_norm.default`:     No decompositions registered for the real-valued input. Example node: `%cudnn_batch_norm : [num_users=1] = call_function[target=torch.ops.aten.cudnn_batch_norm.default](args = (%conv2d, %p_patch_embed_proj_0_1_weight, %p_patch_embed_proj_0_1_bias, %b_patch_embed_proj_0_1_running_mean, %b_patch_embed_proj_0_1_running_var, False, 0.1, 1e-05), kwargs = {})`. All nodes: `[cudnn_batch_norm, cudnn_batch_norm_1, cudnn_batch_norm_2, cudnn_batch_norm_3, cudnn_batch_norm_4, cudnn_batch_norm_5, cudnn_batch_norm_6, cudnn_batch_norm_7, cudnn_batch_norm_8, cudnn_batch_norm_9, cudnn_batch_norm_10, cudnn_batch_norm_11, cudnn_batch_norm_12, cudnn_batch_norm_13, cudnn_batch_norm_14, cudnn_batch_norm_15, cudnn_batch_norm_16, cudnn_batch_norm_17, cudnn_batch_norm_18, cudnn_batch_norm_19, cudnn_batch_norm_20, cudnn_batch_norm_21, cudnn_batch_norm_22, cudnn_batch_norm_23, cudnn_batch_norm_24, cudnn_batch_norm_25, cudnn_batch_norm_26]`
> > 
> > assigned @titaiwangms
> 
> @justinchuby Do we still need this after the decom is fixed?

Maybe not. Thanks!

**Comment by justinchuby** [comment]
- https://github.com/pytorch/pytorch/issues/126774
- https://github.com/pytorch/pytorch/issues/113755
