### ISSUE TITLE
Use IR in the optimizer

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1701]
And improve robustness so it is reliable enough to be turned on by default.

**Comment by justinchuby** [comment]
The ExternalTensor support is working only when code is launched at the same directory as the model file. aka. we read the external data file using relative path. This is because when a model is loaded as a proto, its path information is lost to the IR. We need to design a way to handle when the model file is somewhere else.

This is relevant because I assume the optimizer will sometimes fold external tensors. Some examples may include `Transpose(x)` and element wise computation, casting, etc.

**Comment by gramalingam** [comment]
Related: https://github.com/microsoft/onnxscript/issues/1436
