### ISSUE TITLE
[optimizer] Collapse `Slice`s

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1758]
![image](https://github.com/user-attachments/assets/51adbb0e-d533-4bc1-9141-0c4ea5950bac)

The optimizer currently does not collapse these slices, but there has to be a way to remove them I think?

**Comment by gramalingam** [comment]
Yes, it can be optimized.

Do you know where it is coming from? Just wondering if some change in source onnxscript function is also possible.

**Comment by justinchuby** [comment]
This is coming from the aten slice ops when there iare indexed assignments I believe

**Comment by titaiwangms** [comment]
Found this in a timm model called ghostnet_100, which in onnx_dynamo, it generates 3 slices, while in torchscript, we only use 1. This can be repro on benchmark. cc @xadupre

**Comment by titaiwangms** [comment]
![Image](https://github.com/user-attachments/assets/b9d8888c-d004-4f27-aa7a-c3d5f18cc247)

**Comment by titaiwangms** [comment]
It also happens to slice_scatter as well.

![Image](https://github.com/user-attachments/assets/98850526-6242-4e0e-8862-7acb68f884a3)

**Comment by titaiwangms** [comment]
Investigated more and found these op.Slice should probably be no op, since it's not slicing anything based on the output shape..
