### ISSUE TITLE
Should we separate optimizer and rewriter?

### ISSUE THREAD

**Issue by titaiwangms** [microsoft/onnxscript#1771]
Optimizer actually calls rewriter in its API:
https://github.com/microsoft/onnxscript/blob/main/onnxscript/optimizer/__init__.py#L82

, and it is used in dynamo_export:
https://github.com/pytorch/pytorch/blob/87ddf70fc632a92203375568d5e7fa11adf2713c/torch/onnx/_internal/exporter.py#L1238

But the usage is confusing for the following developmen that the rules are stopped being added to optimizer/__init__.py, for example, https://github.com/microsoft/onnxscript/blob/main/onnxscript/rewriter/llama_rule_sets.py

We should decide to call two APIs, or migrate them to one.

cc @gramalingam @xadupre @justinchuby @shubhambhokare1

**Comment by titaiwangms** [comment]
On benchmark, I think we can default optimizer + rewriter, but we need to decide the API (one or two).

**Comment by gramalingam** [comment]
Agree. I think we should have:

* `optimizer\__init__.py` just expose the core optimizer api (for use by any user).
* The existing implementation of optimize is specific for the pytorch exporter and it should be moved out (either to pytorch repo, or at least a different utility in this repo), which can call the optimizer, and rewriter, with whatever rules it chooses.

**Comment by gramalingam** [comment]
I think this can be closed, with the creation of torch specific optimize API. (The implementation of the API is still ongoing, but the api question is resolved, I think?)
