### ISSUE TITLE
Adding a conditional (if-else logic) and combining several ONNX models into one

### ISSUE THREAD

**Issue by ogencoglu** [microsoft/onnxscript#1774]
I have several ONNX models that have been converted from `scikit-learn` with `skl2onnx`. They take the same numerical features as input. I would like to add a simple if-else logic (let's say based on one of the numerical input variables) to decide which onnx model to route to.

Can I achieve this in onnxscript? Specifically:

- read N onnx models
- write a custom conditional logic at the top
- attach each model's onnx graph to the if-else logic
- save the result as a single ONNX file

The goal is to merge different ONNX files into one with a conditional logic.

**Comment by justinchuby** [comment]
To do this you may consider using the ONNX IR: 

```python
from onnxscript import ir

model_proto= onnx.load(...)
model = ir.from_proto(model_proto)
...
```

You may refer to the inline documentation of the class definition and/or follow up here.

Note that the `If` node in ONNX has only two branches, so you may need to create multiple if nodes (nested) if you have multiple models.

**Comment by ogencoglu** [comment]
Thanks for the swift reply. I will close this for now until I try it properly.
