### ISSUE TITLE
[RFC] Create APIs for pytorch

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1827]
PyTorch calls onnxscript apis and replies on stability of the apis because a single pytorch version can stay for a long time. I propose that we create apis dedicated to a specific version of PyTorch like below. As we evolve our logic we are more free to change user apis like `optimize` without being constrained by existing PyTorch usage. This also allows use to evolve the logic for these apis even after a PyTorch version is released.

```python
onnxscript._framework_apis.torch_2_5.optimize()
onnxscript._framework_apis.torch_2_5.convert_version()
onnxscript._framework_apis.torch_2_5.check_model()
onnxscript._framework_apis.torch_2_5.offload_external_data()
onnxscript._framework_apis.torch_2_5.get_torchlib_ops()
```

cc @gramalingam @xadupre @titaiwangms @shubhambhokare1

**Comment by titaiwangms** [comment]
Are these the only 4 apis? I think I only recognize optimize(). I think as long as ONNX IR doesn't have PyTorch version issue, this is fine.

**Comment by justinchuby** [comment]
Added get_torchlib_ops()
