### ISSUE TITLE
Implement the onnx reference runtime as an eager backend

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#209]
ORT doesn't support float64 and int for many ops, which impacts test coverage.

**Comment by gramalingam** [comment]
Hmmm ... I think eventually, we could switch to using ONNX's reference evaluator, but that's also fairly new and probably needs some more testing and stabilization.

But, realistically, the eventual use is most likely going to be via ORT, and if it is not supported by ORT, it is going to be an issue for production deployment anyway.

**Comment by justinchuby** [comment]
IIRC ort dislikes float64 to control binary size. Maybe default to onnx reference and switch to ort by option? Or the other way around, but for testing purposes I would like to use the reference runtime.
