### ISSUE TITLE
Computed attributes

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#268]
Limitations on attributes makes some ops tricky to implement. For example, `conv1d` requires an attribute that needs to be derived from an input.

Ops like pooling and conv that requires a lot of padding manipulations etc. are constraint by this.

cc @fatcat-z @xiaowuhu

**Comment by gramalingam** [comment]
So, I assume that the current exporter does these computations? So, the question is how best to do in a new onnxscript-based exporter?

**Comment by justinchuby** [comment]
We are now using traced-only functions for this

**Comment by justinchuby** [comment]
e.g.

https://github.com/microsoft/onnx-script/blob/dfaf174a7efaee415223dc628859f7c11318d1f6/onnxscript/function_libs/torch_aten/ops/core.py#L4827-L4846

**Comment by fatcat-z** [comment]
> So, I assume that the current exporter does these computations? So, the question is how best to do in a new onnxscript-based exporter?

@gramalingam ,
Yes, current exporter will finish these computations and pass the final values of those attributes to proper ONNX operator. See [here](https://github.com/pytorch/pytorch/blob/353e9f883fed46cf60e5bc808500ff1a8678241e/torch/onnx/symbolic_opset9.py#L2450) for an example.

Another potential way to do this might be change the signatures of aten_xxx() function so all of such computations would be done out of onnx-script function.

Currently, the compiler will process each statement within an aten_xxx() function and transform them into proper ONNX ops. Is it possible for the compiler to identify some statements which involves attributes only? By this, we can avoid transforming these statements into ONNX ops, but keeping the results of those statements instead.
