### ISSUE TITLE
Attribute before inputs for matching signatures

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#277]
See https://github.com/microsoft/onnx-script/pull/274

**Comment by gramalingam** [comment]
I think this may be the same as https://github.com/microsoft/onnx-script/issues/305

**Comment by justinchuby** [comment]
Duplicate of https://github.com/microsoft/onnx-script/issues/305

**Comment by justinchuby** [comment]
I think this is different since it concerns the function declaration rather than in the call site.
