### ISSUE TITLE
Maybe remove default_opset

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#295]
ONNX has bumped opset version to 19, making onnx_opset_version() to return `("", 19)`, which is not refined in

https://github.com/microsoft/onnx-script/blob/109bf7f16c91de87420d8240699b24a73c07dd86/onnxscript/onnx_opset/__init__.py#L96

failing

https://github.com/microsoft/onnx-script/blob/109bf7f16c91de87420d8240699b24a73c07dd86/onnxscript/onnx_opset/__init__.py#L186-L191

Example failure:

https://github.com/microsoft/onnx-script/actions/runs/3875935285/jobs/6609149688#step:7:1478

cc @abock @gramalingam @fatcat-z @xiaowuhu

**Comment by justinchuby** [comment]
Using the latest main branch onnx build and regenerating the ops did not update [onnx-script/onnxscript/onnx_opset/__init__.py](https://github.com/microsoft/onnx-script/blob/109bf7f16c91de87420d8240699b24a73c07dd86/onnxscript/onnx_opset/__init__.py#L186-L191) for some reason.

**Comment by gramalingam** [comment]
We should probably omit/delete the definition of `default_opset` ... is that what you are suggesting above?

**Comment by justinchuby** [comment]
I think that's a good idea.

I was also confused on why opgen didn't update `__init__`

**Comment by gramalingam** [comment]
> I think that's a good idea.
> 
> I was also confused on why opgen didn't update `__init__`

Ah, ok. There's also the distinction between the current opset version (19) and the last released opset version (18) ... arguably, last released opset version may be more appropriate. But if we delete default_opset, we don't even need to consider this question.

**Comment by justinchuby** [comment]
Sounds like a good plan!

**Comment by justinchuby** [comment]
Done
