### ISSUE TITLE
Shape inference fails on function with string attribute

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#378]
```python
import onnxscript
import onnx
from onnxscript.function_libs.torch_aten.ops.nn import aten_gelu

@onnxscript.script()
def expected_model(x: FLOAT[2, 3, 4]):
    return aten_gelu(x, approximate=False)

expected = expected_model.to_model_proto()

onnx.shape_inference.infer_shapes(expected, True, True)  # Fails
```

E   onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] Shape inference error(s): (op_type:aten_gelu, node name: aten_gelu_0): [ShapeInferenceError] (op_type:Equal, node name: n3): A typestr: T, has unsupported type: tensor(string)

**Comment by gramalingam** [comment]
Interesting, the ONNX Equal op does not support equality comparison on strings: https://github.com/onnx/onnx/blob/main/docs/Operators.md#Equal 

Wonder why. It seems critical if we need to check whether a string-attribute has a given value. I guess we should update the Equal op in ONNX.

**Comment by gramalingam** [comment]
https://github.com/onnx/onnx/issues/1937

**Comment by justinchuby** [comment]
Does it mean we need to split all functions with string into smaller ones?

**Comment by gramalingam** [comment]
> Does it mean we need to split all functions with string into smaller ones?

I don't see how we can do that (may be I am missing something).

I created an ONNX PR to extend the Equal op: https://github.com/onnx/onnx/pull/4828
