### ISSUE TITLE
Function authoring guide for ATen lib 

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#388]
- How to find the signature
- Guide on typing 
    - broadest supported type by the ONNX ops used in the function
- How to test
- #402 
- #412 
- #407 
- #403 
- #400
- #375 
- #293 
- #350 
- #359 
- #411
- Scan
- Avoid trace only. Always add a reason; split the trace only part and make decomposition logic to a function; when to use trace only: dtype attribute, attribute manipulation; trace only requires a static graph.
- Private functions for ONNX
- #419
- https://github.com/microsoft/onnx-script/pull/416
- https://github.com/microsoft/onnx-script/pull/301
- how we handle scalars
- https://github.com/microsoft/onnx-script/pull/428 tricky boolean attributes
- Don’t raise errors #454 
- How to handle ATen overloads; Testing: verify the OpInfo coverage https://github.com/microsoft/onnx-script/pull/463#discussion_r1125165927

**Comment by BowenBao** [comment]
topic suggestion: mutation/aliasing

**Comment by justinchuby** [comment]
the number (0.0) being scripted as constant + castlike https://github.com/microsoft/onnx-script/pull/515#discussion_r1132733650
