### ISSUE TITLE
Prims op support

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#418]
Support prims ops in torch. Need 

1. Code gen from torch._prims.
2. OpInfos for testing.

**Comment by BowenBao** [comment]
Is this for "Prim IR", or are we observing prim ops for fx graphs in "ATen IR"? (IR reference https://pytorch.org/docs/master/ir.html)

**Comment by justinchuby** [comment]
it's for Prims IR. Do we need/ not need them?

**Comment by fatcat-z** [comment]
By calling torch._C._dispatch_get_all_op_names we can filter 189 prims ops in total. 151 of them have corresponding Opinfos in common_methods_invocations.py file while the rest of 38 don't exist.

So I think we can leverage current ops test mechanism and common_methods_invocations.py file for those 151 prims ops. Probably some of them are not implemented under aten namespace and we need to move them to prims.py file.

For the left 38 prims ops, we just need to leverage current extra_opinfo.py to customize the tests. 

So seems we don't need to do any extra work for item 2. Make sense?
