### ISSUE TITLE
Support custom ops

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#475]
Custom ops don’t have a OpSchema. How should we capture them in the evaluator?

**Comment by titaiwangms** [comment]
I think this is only regarding to the custom ops which can't be composed of ONNX ops? (eg: prim::python or myown::conv2d).

**Comment by justinchuby** [comment]
That's right

**Comment by titaiwangms** [comment]
https://github.com/pytorch/pytorch/pull/96013

**Comment by titaiwangms** [comment]
@wschin

**Comment by justinchuby** [comment]
It is now possible to supply an OpSchema
