### ISSUE TITLE
TorchScript Graph: Support model > 2GB

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxscript#493]
Dependent on `torch.Graph._export_onnx`, large model export requires specifying a target path to store the model and weights proto. Right now this path is fixed as "".

https://github.com/microsoft/onnx-script/blob/4986a4be9f8ff1b0e2b7bdde738836574f90e900/onnxscript/function_libs/torch_aten/graph_building.py#L475

**Comment by justinchuby** [comment]
cc @shubhambhokare1

**Comment by BowenBao** [comment]
we do but we need a str path provided. A tedious restriction that we want to eliminate.

**Comment by justinchuby** [comment]
Will we be able to provide an option in `to_model_proto` to leverage what we already have in torch for this?

**Comment by justinchuby** [comment]
Would you like to share some of the options?

**Comment by BowenBao** [comment]
I'm thinking of model / weight separation by default.

**Comment by wschin** [comment]
Can someone please assign this to @wschin? I have a version for demo.

**Comment by justinchuby** [comment]
One thing I think we can do is to save the model out to disk with torchscript, then load it back and pass the model proto onto the exporter for it to decide how to serialize. When we move away from using torchscript this will not be a problem anymore
