### ISSUE TITLE
Rename atenlib to `torch_lib`

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#554]
As we are expanding support to the prim ops, it seems suiting to rename the library to torchlib.

cc @BowenBao @xiaowuhu @fatcat-z @gramalingam @abock

**Comment by fatcat-z** [comment]
Are you going to rename every function's name, from 'aten_' to 'torch_'?

**Comment by justinchuby** [comment]
torch_lib?

**Comment by justinchuby** [comment]
`onnxscript_functions.torch_lib.ops.prims.prims_convert_type`

`pip install onnxscript_functions`

**Comment by justinchuby** [comment]
For package naming for the atenlib, we are thinking the package name onnxscript_functions and the lib exposed as `onnxscript_functions.torch_lib`. In the future other function libs (tf etc.) can live in the same package e.g. onnxscript_functions.tf_lib. Any thoughts?

**Comment by fatcat-z** [comment]
Wondering if onnxscript_function or onnxscript_functions?

**Comment by fatcat-z** [comment]
What does function mean here? onnxscript_utils sounds more general in case we need to add something other than aten/prims functions into it.

Thoughts?

**Comment by justinchuby** [comment]
I would not vote for utils. The functions are onnx functions. Aka it’s a library of onnx functions. We don’t plan to add things other than onnx functions (and supporting components). In the long run I foresee we include tf_lib, numpy_lib etc.
