### ISSUE TITLE
PyTorch FX exporter dispatching and type promotion scenarios

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#563]
1. An ATen op can be dispatched to multiple onnx-script implementations:

`aten::aten_scaled_dot_product_attention` ->

```python
def aten_scaled_dot_product_attention(
    query: TFloat,
    key: TFloat,
    value: TFloat,
    attn_mask: Optional[TFloat] = None,
    dropout_p: float = 0.0,
    is_causal: bool = False,
    scale: Optional[float] = None,
): ...

def aten_scaled_dot_product_attention_bool_mask(
    query: TFloat,
    key: TFloat,
    value: TFloat,
    attn_mask: Optional[BOOL] = None,
    dropout_p: float = 0.0,
    is_causal: bool = False,
    scale: Optional[float] = None,
): ...
```

The exporter will need to dispatch onto one of the implementation based on the dtype of `attn_mask`.

2. (Easy) Multiple ATen op overloads may map to a single onnx-script implementation:

Both `add.Scalar(Tensor self, Scalar other, Scalar alpha=1) -> Tensor` and `add.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> Tensor` map to a single

```python
def aten_add(self: TReal, other: TReal, alpha: float = 1.0) -> TReal: ...
```

# Type promotion

## Pytorch

- [x] `torch_implicit_integral_promotion`: Sometimes we don't need to Cast the output back: `Cast(int to float) -> Cos -> output` https://github.com/pytorch/pytorch/pull/100265#discussion_r1183025474
- [x] `torch_implicit_type_promotion`: ONNX does not have automatic type promotion.
    - We can either run an fx pass to create explicit type promotion nodes before converting to ONNX, or
    - Create rules to promote types in the exporter during conversion.
    - The exporter can consult the `type_constraints` in a function's `OpSchema` to determine whether it needs to cast inputs to the same type.

## ONNX

- [ ] ONNX tends to support less types than PyTorch. When an ONNX function is selected as the dispatch target but it does not support the input type, the exporter needs to insert cast nodes before and after the function. E.g. `Cast -> <the torchlib function> -> Cast` to mirror the aten op's behavior.
- [ ] The exporter may not be able to dispatch to a function with exact type match but can still make a successful dispatch under case (1). For example, we may have two functions supporting `(a) INT64`, `(b) FLOAT32`, and the input is `BFLOAT16`. The dispatcher should be able to choose `(b)` as the target and use the process in (1) to insert proper cast nodes.

cc @titaiwangms @thiagocrepaldi @BowenBao

**Comment by justinchuby** [comment]
## Dispatching logic

**Comment by BowenBao** [comment]
From the perspective of each aten op defines its own type promotion logic, as well as the perspective of eager execution. Could you also discuss the pros/cons/viability of dispatcher/evaluator/OnnxFunction handling automatic type promotion?

**Comment by BowenBao** [comment]
Discussed offline with @titaiwangms.

#### Scratch notes for case of torchlib owning type promotion

* Identify and maintain a set of `type_promotion_kind`s. Each `type_promotion_kind` represents a set of logic of how casting should be done based on arg/output types.
* Decorate torchlib ops with their respective set of `type_promotion_kind`s, which gets populated as attribute of `OnnxFunction` and `OnnxTraceFunction` instance.
* Extend `Evaluator` (or `TypePromotionEvaluator`) to insert proper cast nodes based on `opschema`, actual args/output types, and `type_promotion_kind`s.

<img src="https://github.com/microsoft/onnxscript/assets/9376104/de5dd963-73c9-40b5-8139-37fe6348f554" width="65%" height="65%" />

**Comment by justinchuby** [comment]
## Rules

- Need one for each op, or are most of them defaults?

E.g.

```
add(float16, float32) -> float32
```

1. FX pre-pass: rules defined in PyTorch
-> Meta - maybe enrich native_functions.yaml? | Hard
-> Hardware dependent?
Pros: Can compare FX graph to FX graph (good for debugging)

Many casts can show up after the pass?
-> Node correspondence?

2. Use the input types and Schema alone -> Trying to reduce the need for maintaining a set of rules.
  (need pytorch rules?)

3. ONNX Script torchlib functions will be decorated with type promotion rules

Will they need the same set of info?
-> (2) may not

If we maintain the rules in onnxscript, how do we handle evolution or different hardware?

- [x] Two step casting: (a) Insert explicit casts in FX (b) adapt to ONNX
(That's (1)+(2))

* autocast should be explicit already

## Implicit / Explicit logic in onnxscript

Evaluator: promotion is op specific?

ONNX invariants:

- Input types need to match the constraints, with or without upcast rules.


torch arg -> onnx arg: opschema promotion: Users using onnxscript may expect this
pytorch: pytorch output -> 

For now not implement the logic in the Evaluator but do it in the converter.


## Notes

- Metadata in FX passes that documents who/why Cast nodes are added. Associated nodes etc.
- General to other FX passes too.
- We would like things to be composable

**Comment by justinchuby** [comment]
How PyTorch registers the promotion rules:

```python
@register_decomposition(aten.where)
@out_wrapper()
@elementwise_type_promotion_wrapper(
    type_promoting_args=("a", "b"),
    type_promotion_kind=ELEMENTWISE_TYPE_PROMOTION_KIND.NO_OPMATH,
)
def where(
    pred: Tensor,
    a: Optional[TensorOrNumberLikeType] = None,
    b: Optional[TensorOrNumberLikeType] = None,
):
```

https://github.com/pytorch/pytorch/blob/51664489ba6f6b2343bbec9af9ca99185e2a5dbc/torch/_refs/__init__.py#L1856C1-L1866C3

**Comment by justinchuby** [comment]
Type comparison: https://github.com/pytorch/pytorch/blob/23b7035b3c61b0900e900e39ba7e69997a417ea8/torch/_prims_common/__init__.py#L1073

```python
class ELEMENTWISE_TYPE_PROMOTION_KIND(Enum):
    DEFAULT = (0,)
    NO_OPMATH = (1,)
    INT_TO_FLOAT = (2,)
    ALWAYS_BOOL = (3,)
    COMPLEX_TO_FLOAT = (4,)
    BOOL_TO_LONG = (5,)


class REDUCTION_OUTPUT_TYPE_KIND(Enum):
    SAME = (0,)
    COMPLEX_TO_FLOAT = (1,)  # for complex types outputs corresponding real type
    KEEP_PROMOTED_TYPE = (2,)  # keep output in opmath type, needed for mean
    ALWAYS_BOOL = (3,)
```

Usage: https://github.com/pytorch/pytorch/blob/23b7035b3c61b0900e900e39ba7e69997a417ea8/torch/_prims_common/__init__.py#L1291-L1333

**Comment by thiagocrepaldi** [comment]
@justinchuby should we close this?

**Comment by thiagocrepaldi** [comment]
np.
is it possible to add the missing/completed tasks to help us know what is and is not done?

**Comment by thiagocrepaldi** [comment]
@justinchuby  should this be closed?

**Comment by justinchuby** [comment]
Yes. Thanks!

For reference, The two points under ONNX (1) is not needed in practice; (2) is handled by overloads
