### ISSUE TITLE
[torchlib] Complex operator support

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#693]
ONNX operators don't support complex numbers. This makes it hard to exactly recreate operators like `torch.stft` whose output is complex. A proposal is https://github.com/onnx/onnx/issues/4785 to enable complex-real conversion.

As an alternative, @gramalingam suggested we can do some careful tracking to get around this problem during export. Here is something we can do:

### Design exploration

1. In `torchlib`, we can create complex overloads of the ops we want to support, such as `aten_stft` or `aten_abs_complex`.
2. In torch, we know when an input/output of an op is complex. We can use this information and dispatch to the correct complex overload of an operator.
3. When a tensor is complex, we internally use a real representation where the last two dimensions are the real and the imaginary parts. As an example, the graph

```mermaid
flowchart TD
input --real--> torch.stft --complex--> torch.abs --real--> output
```

becomes

```mermaid
flowchart TD
input --real--> aten_stft --real representation of complex--> aten_abs_complex --real--> output
```

in ONNX. This is as though we have the graph

```mermaid
flowchart TD
input --real--> aten_stft --real representation of complex--> ViewAsComplex --complex--> ViewAsReal --real representation of complex--> aten_abs_complex --real--> output
```

and ran an optimization pass to cancel out the `ViewAsComplex` and `ViewAsReal` node pairs.

### Implications

This implies that we will not be able to match exactly any ops that deals with complex numbers in ONNX Script with torch. So we may need special handling when setting dtype etc. in the converted graph. We may also need a dispatching mechanism that leverages information that is not in OpSchema to dispatch to a complex op, because a complex op will have an identical signature as its real counterpart (e.g. `abs `and `abs_complex` will have the same function signature).

@titaiwangms @BowenBao @gramalingam

**Comment by justinchuby** [comment]
```python

def abs(a: TReal) -> TReal:
    return op.Abs(a)

def abs_complex(a: COMPLEX64[4,3]) -> COMPLEX64:
    # But we cannot handle complex numbers
    pass

def abs_complex(a: FLOAT32[4,3,2]) -> FLOAT32:
    return op.Sqrt(op.Power(a[..., 0], 2) + op.Power(a[..., 1], 2))
```

**Comment by justinchuby** [comment]
Shape assignment: In FX when we see complex with shape [...], we change it to [..., 2] and supply it to onnx.

**Comment by justinchuby** [comment]
torch.complex64 -> FLOAT32
torch.complex128 -> FLOAT64

**Comment by titaiwangms** [comment]
#4785
