### ISSUE TITLE
[torchlib] Implement mean

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxscript#703]
https://github.com/pytorch/pytorch/blob/3e3cf02c44f33d050e12eca4b28cabc1c2ee1aa3/test/onnx/test_fx_to_onnx_with_onnxruntime.py#L306

**Comment by justinchuby** [comment]
@xiaowuhu could you help take a look? Thanks!

**Comment by titaiwangms** [comment]
@xiaowuhu Do you have time to work on this? [TorchBench](https://github.com/microsoft/onnx-converters-private/issues/166) shows that this op basically blocks lots of model, so we figure if we can support it, then we can rocket-increase model coverage.

**Comment by xiaowuhu** [comment]
@justinchuby @titaiwangms Just notice this message, sorry for the late. I will take a look soon.

**Comment by titaiwangms** [comment]
Thank you very much!
