### ISSUE TITLE
Auto computed type constraints for functions

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#706]
Currently the type constraints for onnx functions in the generated OpSchemas are hand specified (e.g. `TReal` etc.). Since the graph in a function is fully defined, we may be able to generate the type constraints as well (using some graph algorithms) and automatically update/correct the type annotations in the function definitions.

cc @xiaowuhu @fatcat-z @titaiwangms @BowenBao @gramalingam

**Comment by titaiwangms** [comment]
@abock Is the next step of https://github.com/microsoft/onnxscript/pull/768 this issue?
