### ISSUE TITLE
Flaky CI: worker 'gw0' crashed while running xxx

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxscript#761]
Some example runs:
https://github.com/microsoft/onnxscript/actions/runs/5138839927/jobs/9248599814?pr=755
https://github.com/microsoft/onnxscript/actions/runs/5149591642/jobs/9272793720?pr=759
https://github.com/microsoft/onnxscript/actions/runs/5159201503/jobs/9293826467?pr=758

**Comment by justinchuby** [comment]
Some flaky ort again:

https://github.com/microsoft/onnxscript/actions/runs/5225635296/jobs/9435363354#step:5:14132

`[gw1] win32 -- Python 3.10.11 D:\a\onnxscript\onnxscript\.nox\test_torch_nightly\Scripts\python.EXE
worker 'gw1' crashed while running 'onnxscript/tests/function_libs/torch_lib/ops_test.py::TestOutputConsistencyFullGraphCPU::test_output_match_opinfo__min_other_binary_cpu_float16'`

**Comment by justinchuby** [comment]
So far they look like ops related to ReduceMin / ReduceMax

**Comment by BowenBao** [comment]
And so far windows only?

**Comment by justinchuby** [comment]
I've seen linux once or twice

**Comment by jcwchen** [comment]
Are these 2 tests (`test_output_match_opinfo__maximum_cpu_float16` and `test_output_match_opinfo__minimum_cpu`) also flaky? I saw them failed on Windows in a few PRs which seem irrelevant. Since it happened quite often, perhaps we can skip these tests on Windows for now?

**Comment by justinchuby** [comment]
Sure, I will add a skip

**Comment by justinchuby** [comment]
https://github.com/microsoft/onnxruntime/issues/16492
