### ISSUE TITLE
aten_unfold needed for Whisper

### ISSUE THREAD

**Issue by abock** [microsoft/onnxscript#783]
We need to implement [`aten_unfold`](https://github.com/microsoft/onnxscript/blob/main/onnxscript/function_libs/torch_lib/ops/core.py#L6351-L6368), possibly the other variants as this will come up when exporting [Whisper](https://github.com/openai/whisper/blob/main/whisper/timing.py#L49) through the Dynamo exporter.

cc @kunal-vaishnavi, @thiagocrepaldi, @justinchuby

**Comment by BowenBao** [comment]
Surprised whisper is not part of torchbench. 

@MaanavD might be good practice contributing this model to torchbench, as material for your tutorial.

**Comment by MaanavD** [comment]
@BowenBao Yep, actually that's the second request I've had for Whisper in Torchbench, I will look into it shortly!
