### ISSUE TITLE
Questions around _aten_native_batch_norm_inference_onnx

### ISSUE THREAD

**Issue by abock** [microsoft/onnxscript#786]
[As commented](https://github.com/microsoft/onnxscript/pull/773#pullrequestreview-1482443336) in #773, @gramalingam is curious what the intent of these lines are:

https://github.com/microsoft/onnxscript/blob/f106c1e906cb05ffc37491c9111402779e79de2d/onnxscript/function_libs/torch_lib/ops/core.py#L4435-L4438

**Comment by justinchuby** [comment]
I think it is saying onnxscript wouldn't allow

```python
    ...
    empty = op.Cast(op.Shape(input, start=0, end=0), to=FLOAT.dtype) 
    return norm, empty, empty
```

Perhaps

```python
    ...
    empty_mean = op.Cast(op.Shape(input, start=0, end=0), to=FLOAT.dtype)
    empty_var = empty_mean
    return norm, empty_mean, empty_var
```

works? Or we can update the translator to account for this.

@xiaowuhu feel free to add or correct

**Comment by xiaowuhu** [comment]
```
a = op.Cast(xxxx)
b = a
```
This lines cannot work in onnxscript, because they are actually one var.   ```b = op.Identity(a)``` can work.

**Comment by gramalingam** [comment]
I understand the comment and the duplicated lines. What I am puzzled by is: what is the actual value it is trying to return? Why is the first dimension value being returned as a "mean" and "variance"? Something seems off. Why is it called "empty_*" ? Is it a case where the returned value doesn't matter? Then, why invoke "Shape" at all?

**Comment by gramalingam** [comment]
May be it is trying to create a don't-care value of the given dimension? Then, the code is wrong, and needs an Expand perhaps.

**Comment by xiaowuhu** [comment]
For the test case of aten_native_batch_norm(), one case's expected result should be:
```
[tensor([[[ -1.7358, ...0.4818]]]), tensor([]), tensor([])]
```
So we need make sure the first element ```tensor([[[ -1.7358, ...0.4818]]])``` is correct, it is correct.
But for the second and third element, they must be empty tensor. In onnxscript, I didn't find any other way to create a real empty tensor.

**Comment by gramalingam** [comment]
By the way, the explicit call to `make_tensor` also specifies the exact output shape required. An empty tensor can have many different shapes, so may be good to be explicit about that too.

**Comment by justinchuby** [comment]
I personally don’t enjoy the fact that we have to specify and maintain a unique name to the make tensor call. It would be nice to have an onnxscript equivalent with a simpler api, as I avoid importing onnx and using any of the helpers in torchlib

**Comment by gramalingam** [comment]
> I personally don’t enjoy the fact that we have to specify and maintain a unique name to the make tensor call. It would be nice to have an onnxscript equivalent with a simpler api, as I avoid importing onnx and using any of the helpers in torchlib

Right, we should have better `helper` apis in onnxscript for creating values.

**Comment by xiaowuhu** [comment]
We also need API about creating an empty tensor with specified shape.
