### ISSUE TITLE
[torchlib] Revisit empty_var

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#790]
> May be it is trying to create a don't-care value of the given dimension? Then, the code is wrong, and needs an Expand perhaps.

_Originally posted by @gramalingam in https://github.com/microsoft/onnxscript/issues/786#issuecomment-1594907255_

**Comment by xiaowuhu** [comment]
This is refine, but not sure there have some better way to create empty tensor in OnnxScript.
https://github.com/microsoft/onnxscript/pull/902
