### ISSUE TITLE
Is it possible to create multi layer large model using onnxscript?

### ISSUE THREAD

**Issue by kailums** [microsoft/onnxscript#820]
Hi guys

I want to use onnxscript to create a transformer-like model which contains multi-blocks, each block has same structure. so i implement using onnxscript like this

```
@script()
def block(x):
    x = op.MatMul(x, w)
    x = op.ReLU(x)
    x = op.MatMul(x, w)
    return x

# here I use for loop to create multi-layers of block
layers=2
@script(default_opset=opset15)
def model(x):
    for i in range(layers):
        x = block(x)
    return x
```

I want to get a model structure like this:
![image](https://github.com/microsoft/onnxscript/assets/109063327/c5e2bbd6-e8c1-448b-b557-77fdd589df43)

But it seems not work. it convert for-loop into a layer with loop body is a block function, and can't be running in onnxruntime, raise segment fault.

![image](https://github.com/microsoft/onnxscript/assets/109063327/bfe3e9ca-5f06-4900-a466-38a347e507e1)
![image](https://github.com/microsoft/onnxscript/assets/109063327/7c5a33df-881c-47fd-b338-3787185f9eac)

Is it possible to unroll this for loop, directly call into the block? just like the torch module.

**Comment by justinchuby** [comment]
cc @gramalingam an interesting use case here

**Comment by gramalingam** [comment]
(i) Agree that being able to unroll loops would be a useful feature.

(ii) Why ORT crashes is another issue: looks like a bug that should be fixed.

**Comment by thiagocrepaldi** [comment]
With the recent `trace_ok` feature, onnxscript has the ability to have traced (static) and not-traced (dynamic) function implementation. 

I wonder if we could extend this further and provide a mix and match static and dynamic implementations, similar to how we can mix `torch.jit.script` and `torch.jit.trace`. Refer to https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting for the core idea

That is, we can have some static functions that wrap dynamic functions and/or vice-versa. On @kailums issue, he could have an traced function with the loop and the body of the loop would call a dynamic onnx function.

**Comment by justinchuby** [comment]
> have an traced function with the loop and the body of the loop would call a dynamic onnx function.

this should work!
