### ISSUE TITLE
Allow `ConstantOfShape` to take python constants

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#860]
Instead of writing 

```python
op.ConstantOfShape(
    new_shape, value=make_tensor("zerof", TensorProto.FLOAT, [1], [0])
)
```

it would be great to be able to write

```python
op.ConstantOfShape(
    new_shape, value=0.0)
)
```

cc @gramalingam

**Comment by gramalingam** [comment]
Yes, that would be nice. It is best done by utilizing type information for attributes from the opschema, since attributes can be ints or floats or tensorsL: we don't want to promote a float-typed attribute into a tensor-attribute.

**Comment by gramalingam** [comment]
I think this works now? Closing it, please feel free to reopen in case of problems.
