### ISSUE TITLE
Annotate overload information on torchlib functions

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#865]

**Comment by BowenBao** [comment]
List of unannotated ops found in diagnostics from onnx bench. @justinchuby @titaiwangms 

```
{'aten.add.Tensor': 30596,
 'aten.clamp.Tensor': 2330,
 'aten.div.Tensor': 9528,
 'aten.eq.Scalar': 72,
 'aten.eq.Tensor': 112,
 'aten.fill.Tensor': 28,
 'aten.ge.Scalar': 4,
 'aten.ge.Tensor': 4,
 'aten.gt.Scalar': 45,
 'aten.le.Tensor': 32,
 'aten.lt.Scalar': 80,
 'aten.mul.Tensor': 20459,
 'aten.ne.Scalar': 612,
 'aten.roll.default': 22,
 'aten.rsub.Scalar': 358,
 'aten.select.int': 4532,
 'aten.slice.Tensor': 15708,
 'aten.split.Tensor': 2331,
 'aten.sub.Tensor': 6945,
 'aten.transpose.int': 12068,
 'aten.unbind.int': 832,
 'aten.where.self': 578}
```

**Comment by justinchuby** [comment]
aha! do you have a list you are working on? I didn't do anything yet

**Comment by BowenBao** [comment]
https://github.com/microsoft/onnxscript/pull/919

**Comment by BowenBao** [comment]
There is `aten::div.Tensor_Mode` left, which should be unsupported, but somehow worked with fallback.

**Comment by BowenBao** [comment]
> There is `aten::div.Tensor_Mode` left, which should be unsupported, but somehow worked with fallback.

Tracked by https://github.com/pytorch/pytorch/issues/106057, along with other exporter dispatcher nearest match warnings.

**Comment by titaiwangms** [comment]
> There is `aten::div.Tensor_Mode` left, which should be unsupported, but somehow worked with fallback.

Fallback seems reasonable, given the current implementation. However, there is one perfect match for this op in th sarif you provided in https://github.com/pytorch/pytorch/issues/106057. That seems like a big bug lol.
