### ISSUE TITLE
Translate `bool` attributes to BOOL when it is promoted to input

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#872]
Currently `bool` is treated as int and will be promoted to INT64 when it is used as an input. For a Pythonic experience and to reduce errors it would be good to promote it to BOOL.

@gramalingam

**Comment by gramalingam** [comment]
Right. I think you may even have an earlier issue about this. I thought a bit about it. It is doable directly when promoting an attribute-reference of bool type to a value.

Another point to consider is another feature (which is currently missing in auto-cast): inserting casts on constants when the target type is known: e.g., in the call `SomeOp(1, ...)` where the first argument is known to be of "float type". We could insert a cast to float for the constant 1 here. Such a feature would also solve the above issue in almost all normal use-cases. In addition, it would also handle the case where an int attribute is used as an argument where a bool tensor is expected.

But if we do both, we may end up producing some redundant casts in cases like this. I guess that's one reason I didn't complete that right away. But maybe we should do this feature (bool attribute promotion) first, anyway ... any thoughts?

**Comment by justinchuby** [comment]
I think having the BOOL promotion first is going to be very useful, because it is going to eliminate a class of errors otherwise detected only when running the model. 

For the other autocast feature I wonder how many ops there are where the type requirement is definitive, ie a single type like float? If the op takes multiple different types, do we need to look at other inputs for the analysis? Should we cast int to float16/float32/float64 for example? Should we do it for python constants, or onnx attributes / onnx constants as well? (I still think it should be a good idea, just typing out what I was wondering when exploring this!)

At the same time, I wonder if it is possible to do additional analysis to remove consecutive casts?

**Comment by gramalingam** [comment]
> If the op takes multiple different types, do we need to look at other inputs for the analysis?

Yes. This is done already, and introduces a `CastLike`, so something like `X+1` will be translated correctly for all types of `X`.

**Comment by justinchuby** [comment]
I wonder what happens for `(const1 + const2) + dynamic_x`. Will there be a castlike for each add? When the dtypes are different for each value, would that mean + is not commutative? Is that an issue?

**Comment by gramalingam** [comment]
Good question. I think nothing happens in this case, for these reasons. For now, the workaround is that the user does this themselves (eg., they can compute `const1 + const2` outside the script (using python semantics, and doing whatever they wish) and use only the `result` inside the script.) So, it is a problem to be solved (in the converter).
