### ISSUE TITLE
op.While cannot be inside op.If

### ISSUE THREAD

**Issue by xiaowuhu** [microsoft/onnxscript#879]
If the script looks like:
```
cond = ...
while cond:
   ...
```
It works well. But if the script looks like:
```
cond1 = ...
if cond1:
    cond2 = ...
    while cond2:
        ....
```
It cannot pass the stmt checking for the op.While().

cc @gramalingam

**Comment by gramalingam** [comment]
I think this should work now? I will close it. Please reopen if there is any issue, thanks!
