### ISSUE TITLE
[torchlib] Fix hstack and vstack, atleast_*_sequence

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#960]
hstack: `RUNTIME_EXCEPTION : Exception during initialization: Invalid tensor data type 0.`
vstack: `[ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: Duplicate definition of name (_0x62afb00_rank)`
atleast_*_sequence: `[ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: Duplicate definition of name (_0x9370ed0_rank)`

**Comment by titaiwangms** [comment]
This should be fixed. Looks like the one I had when I write these ops..
https://github.com/microsoft/onnxruntime/issues/16296

Might be related

**Comment by justinchuby** [comment]
Do you know how to take the fix or make the tests pass?

**Comment by justinchuby** [comment]
Thanks!
